### ISSUE TITLE
Unecessary post-install

### ISSUE THREAD

**Issue by Downchuck** [ORESoftware/json-parser#1]
There's a post-install script that seems unneeded. Noticed it when I ran this via alpine node

**Comment by ORESoftware** [comment]
yeah you're right, it's pretty much a no-op right now

https://github.com/ORESoftware/json-parser/blob/master/assets/postinstall.sh

I will clean that up, thanks for the heads up

**Comment by ORESoftware** [comment]
Cleaned it up, also added a performance boost in the codebase. This is a really solid json-parsing library, I hope you like and realize how simple and easy to use it is!

new version with fixes:

```
  "name": "@oresoftware/json-stream-parser",
  "version": "0.0.109",
```

so install

```
$ npm i @oresoftware/json-stream-parser@0.0.109
```

**Comment by Downchuck** [comment]
Yep it made my work a breeze; piping json from stdin for integration testing a service that normally sees calls via http.

**Comment by ORESoftware** [comment]
nice good to hear, yeah this has to be one of the simplest implementations of this, I was looking at the source of some other packages that claimed to do this and I couldn't believe some of the code so I wrote this

**Comment by Downchuck** [comment]
Ran across a post from you in 2017 about some legacy typescript; thanks for that too!
https://github.com/Microsoft/TypeScript/issues/20273

**Comment by ORESoftware** [comment]
ah yes now I know that TS is prolly what sold this package to you, I dont understand how ppl can do the world a disservice and not write libs in TS

**Comment by ORESoftware** [comment]
@Downchuck fixed a bug - a try/catch block was swallowing user-land errors, install this version for an update:

`@oresoftware/json-stream-parser@0.0.113`

api hasn't changed, just a bugfix - this was the bug https://github.com/nodejs/help/issues/1900
